### ISSUE TITLE
Building error of SE2P

### ISSUE THREAD

**Issue by wenyan4work** [ludvigak/SE_unified#1]
Hello!

I am compiling this code with gcc 4.8.5 and MATLAB R2016b. The CMAKE stage completed and the 'run_unit_tests' routine in the root folder completed without error. The 3D stokes spectral code works very well.

When I am trying to use the 2P code (SE2P and SE2P_Stokes), after typing 'make' in the folder within Matlab, I got building errors from MEX. It seems that the macro '__FGG_EXPA_FORCE' is not properly preprocessed with the script. 

Do I need to modify the 'CFLAGS' to fix this issue?

Thank you!

This is the output from the matlab command window: 
```matlab
>> clear all
>> make
Building with 'gcc'.
/home_local/software/SEStokes/SE_unified/SE2P_Stokes/../SE_fast_gridding/mex/SE_fg_grid_mex.c: In function ‘mexFunction’:
/home_local/software/SEStokes/SE_unified/SE2P_Stokes/../SE_fast_gridding/mex/SE_fg_grid_mex.c:33:5: warning: passing argument 2 of ‘mxCreateNumericArray_700’ from incompatible pointer type [enabled by default]
     H_OUT = mxCreateNumericArray(3, dims, mxDOUBLE_CLASS, mxREAL);
     ^
In file included from /home_local/software/MATLAB/R2016b/extern/include/mex.h:51:0,
                 from /home_local/software/SEStokes/SE_unified/SE2P_Stokes/../SE_fast_gridding/mex/SE_fg_grid_mex.c:1:
/home_local/software/MATLAB/R2016b/extern/include/matrix.h:786:1: note: expected ‘const int *’ but argument is of type ‘size_t *’
 mxCreateNumericArray_700(int ndim, const int *dims, mxClassID classid, mxComplexity flag);
 ^

/home_local/software/SEStokes/SE_unified/SE2P_Stokes/../SE_fast_gridding/SE_fgg.c: In function ‘SE_FGG_expand_all_SSE_force’:
/home_local/software/SEStokes/SE_unified/SE2P_Stokes/../SE_fast_gridding/SE_fgg.c:856:2: warning: implicit declaration of function ‘__FGG_EXPA_FORCE’ [-Wimplicit-function-declaration]
  *(work->idx+n) = __FGG_EXPA_FORCE(xn,1,params, 
  ^

Error using mex
/tmp/mex_1123543245588658_32321/SE_fgg.o: In function `SE_FGG_expand_all_SSE_force':
SE_fgg.c:(.text+0x1e30): undefined reference to `__FGG_EXPA_FORCE'
/tmp/mex_1123543245588658_32321/SE_fgg.o: In function `SE_FGG_int_force':
SE_fgg.c:(.text+0x2836): undefined reference to `__FGG_EXPA_FORCE'
collect2: error: ld returned 1 exit status


Error in make (line 24)
eval([mex_string ' -DTWO_PERIODIC -DVERBOSE ../SE_fast_gridding/mex/SE_fg_grid_mex.c ../SE_fast_gridding/SE_fgg.c
../SE_fast_gridding/SE_fgg_MEX_params.c'])

```

**Comment by wenyan4work** [comment]
SE2P and SE2P_Stokes cannot compile by adding '-I../SE_fast_gridding/' to the cflags.

By adding -I../SE_fast_gridding/ to the cflags, I managed to compile the case in 'SE' folder
but when I execute 'test_accuracy', MATLAB reports a fatal error:

```matlab
SE_opt = 

  struct with fields:

    M: [28 28 28]

[EWALD (FD3P)] MEX N=(10,10) xi = 4.00 [rc = -1.00, layers=13]

leg =

  cell

    'm = 5.0'

[ SE ] Grid: [28 28 28]	Gaussian: {P = 5, w=0.09, m=5}
[ SE ] Gridding method: fgg mex {eta=0.02, c=1568.00}

```
Then it reports a fatal error where MATLAB must be closed and restarted. The error details shows a line related to SE_fg_grid_mex:

```matlab
[  1] 0x00007fb1dd9e2d5a /home_local/software/SEStokes/SE_unified/SE/bin/SE_fg_grid_mex.mexa64+00003418 mexFunction+00000186
```

**Comment by wenyan4work** [comment]
The first problem is due to the function in line 842 of SE_fgg.c:
```c

// -----------------------------------------------------------------------------
void SE_FGG_expand_all_SSE_force(SE_FGG_work* work, 
				 const SE_state* st, 
				 const SE_FGG_params* params)
{
    double xn[3] MEM_ALIGNED;
    
    const int N = params->N;
    const int P = params->P;

    for(int n=0; n<N; n++)
    {
	// compute index and expansion vectors
	xn[0] = st->x[n]; xn[1] = st->x[n+N]; xn[2] = st->x[n+2*N];
	
	*(work->idx+n) = __FGG_EXPA_FORCE(xn,1,params, 
					  work->zx+n*P, 
					  work->zy+n*P, 
					  work->zz+n*P,
					  work->zfx+n*P,
					  work->zfy+n*P,
					  work->zfz+n*P);
    }
}

```

where the macro '__FCC_EXPA_FORCE' is undefined for TWO_PERIODIC:

``` c
#ifdef TWO_PERIODIC
#define __FGG_EXPA fgg_expansion_2p
#define __FGG_INDEX fgg_index_2p
#define PER_STR "2P"
#endif
```

is there a 2p version of the corresponding macro for 3p? Can I just comment out the above block?
``` c
#ifdef THREE_PERIODIC
#define __FGG_EXPA fgg_expansion_3p
#define __FGG_EXPA_FORCE fgg_expansion_3p_force
#define __FGG_INDEX fgg_index_3p
#define PER_STR "3P"
#endif
```

**Comment by ludvigak** [comment]
Hi! I'm happy that you're interested in the SE code.
The 2P part has not been maintained for a while, and the whole framework with cmake and unit tests only covers the 3P parts so far. If you're interested I'd be happy to have a look at what's needed to get the 2P parts up and running again, but I can't do that until next week.

**Comment by davoudss** [comment]
Hello! I fixed the issue. It should work now. Please build the code using cmake. You may want to provide TWO_PERIODIC instead of THREE_PERIODIC in the CMakeLists.txt and build.

**Comment by wenyan4work** [comment]
Hello! thanks a lot for the fix!

When CMakeList.txt is set to TWO_PERIODIC, the SE2P_Stokes test_accury works fine.

But when CMakeList.txt is set to THREE_PERIODIC, one of the unit test fails:
I did some simple test and found that    'test_kspace_out/test_kspace_out'                false     true      true           3.9853     [1×1 struct] ' seems to be broken in the run_unit_tests.m:

```matlab
Results from SE_Stresslet:

                        Name                         Passed    Failed    Incomplete    Duration      Details   
    _____________________________________________    ______    ______    __________    ________    ____________

    'test_direct_real_fast/test_direct_real_fast'    true      false     false         0.53748     [1×1 struct]
    'test_direct_xi_indep/test_direct_xi_indep'      true      false     false          3.6191     [1×1 struct]
    'test_eval_external/test_eval_external'          true      false     false         0.11783     [1×1 struct]
    'test_fast_summation/test_fast_summation'        true      false     false         0.71402     [1×1 struct]
    'test_kspace_out/test_kspace_out'                false     true      true           3.9853     [1×1 struct]
    'test_net_flow/test_net_flow'                    true      false     false          1.4844     [1×1 struct]
    'test_real_rc/test_real_rc'                      true      false     false         0.54535     [1×1 struct]
    'test_rs_sing_sub/test_rs_sing_sub'              true      false     false         0.28213     [1×1 struct]
    'test_sse/test_sse'                              true      false     false          2.9088     [1×1 struct]
    'test_stresslet_unity/test_stresslet_unity'      true      false     false         0.32367     [1×1 struct]
```

Also, it seems that the 2P and 3P version cannot coexist in the same build. Is it correct?

**Comment by ludvigak** [comment]
Right, this fix is not optimal since 2P and 3P cannot coexist this way. What we need to do is change the build of the FGG code such that we build two versions of it, i.e. fgg_2p and fgg_3p . I have a pretty clear idea of what needs to be done, but I can't look at it until next week.

**Comment by wenyan4work** [comment]
Thanks a lot!

I'm working on the Stokes 2p case and hopefully I can contribute my
extension codes soon.

Best,

On Mar 1, 2017 10:02, "Ludvig af Klinteberg" <notifications@github.com>
wrote:

Right, this fix is not optimal since 2P and 3P cannot coexist this way.
What we need to do is change the build of the FGG code such that we build
two versions of it, i.e. fgg_2p and fgg_3p . I have a pretty clear idea of
what needs to be done, but I can't look at it until next week.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ludvigak/SE_unified/issues/1#issuecomment-283363884>,
or mute the thread

**Comment by ludvigak** [comment]
Ok.
Now Cmake build is updated such that both 2P and 3P codes should work. At least the unit tests run and the test_accuracy scripts of SE2P and SE2P_Stokes seem to be doing somthing nice. 

Note however that the unit tests are not all-covering, and specifically do not cover the 2P codes at all.
